const KEY='mi-agenda-v1';let data=JSON.parse(localStorage.getItem(KEY)||'{"movements":[],"payments":[],"tasks":[]}');let cal=new Date();
const money=n=>'Bs '+Number(n||0).toLocaleString('es-BO',{minimumFractionDigits:0,maximumFractionDigits:2});
const fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('es-BO',{day:'2-digit',month:'short',year:'numeric'});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem(KEY,JSON.stringify(data));render();toast('Guardado correctamente')}
function totals(){let i=data.movements.filter(x=>x.type==='income').reduce((a,x)=>a+ +x.amount,0),e=data.movements.filter(x=>x.type==='expense').reduce((a,x)=>a+ +x.amount,0);return{i,e,b:i-e}}
function render(){const t=totals(),now=new Date(),h=now.getHours();document.getElementById('balance').textContent=money(t.b);document.getElementById('income').textContent=money(t.i);document.getElementById('expense').textContent=money(t.e);document.getElementById('financeBalance').textContent=money(t.b);document.getElementById('financeIncome').textContent=money(t.i);document.getElementById('financeExpense').textContent=money(t.e);document.getElementById('incomeCount').textContent=data.movements.filter(x=>x.type==='income').length+' ingresos';document.getElementById('expenseCount').textContent=data.movements.filter(x=>x.type==='expense').length+' egresos';let pending=data.payments.filter(x=>x.status!=='paid');document.getElementById('pendingAmount').textContent=money(pending.reduce((a,x)=>a+ +x.amount,0));document.getElementById('pendingCount').textContent=pending.length+' pendientes';document.getElementById('greeting').textContent=(h<12?'¡Buenos días':h<19?'¡Buenas tardes':'¡Buenas noches')+', Jeason! 👋';document.getElementById('todayLabel').textContent=now.toLocaleDateString('es-BO',{weekday:'long',day:'numeric',month:'long',year:'numeric'});renderMovements();renderPayments();renderCalendar();renderTasks();renderChart();renderWeekly()}
function movementItem(x){return `<div class="movement"><div class="mleft"><div class="micon">${x.type==='income'?'↗':'↘'}</div><div><div class="mname">${esc(x.title)}</div><div class="meta">${esc(x.category||'General')} · ${fmt(x.date)}</div></div></div><div class="amount ${x.type==='income'?'income':'expense'}">${x.type==='income'?'+':'−'}${money(x.amount)}</div></div>`}
function renderMovements(){let s=[...data.movements].sort((a,b)=>b.date.localeCompare(a.date));document.getElementById('recent').innerHTML=s.slice(0,5).map(movementItem).join('')||'<div class="empty">No hay movimientos registrados.</div>';document.getElementById('allMovements').innerHTML=s.map(movementItem).join('')||'<div class="empty">Registra tu primer movimiento.</div>'}
function paymentItem(p){return `<div class="movement"><div class="mleft"><div class="micon">◷</div><div><div class="mname">${esc(p.title)}</div><div class="meta">${fmt(p.date)} · ${esc(p.category||'General')}</div></div></div><div style="text-align:right"><div class="amount" style="color:#b7791f">${money(p.amount)}</div><button class="link" onclick="pay('${p.id}')">${p.status==='paid'?'Pagado':'Marcar pagado'}</button></div></div>`}
function renderPayments(){let p=[...data.payments].sort((a,b)=>a.date.localeCompare(b.date)),pending=p.filter(x=>x.status!=='paid');document.getElementById('paymentsList').innerHTML=p.map(paymentItem).join('')||'<div class="card empty">No tienes pagos registrados.</div>';document.getElementById('homePayments').innerHTML=pending.slice(0,3).map(paymentItem).join('')||'<div class="empty">No hay pagos pendientes.</div>'}
function pay(id){let p=data.payments.find(x=>x.id===id);if(!p||p.status==='paid')return;p.status='paid';data.movements.push({id:crypto.randomUUID(),type:'expense',title:p.title,amount:p.amount,category:p.category,date:new Date().toISOString().slice(0,10)});save()}
function renderTasks(){let t=data.tasks.filter(x=>!x.done);document.getElementById('tasks').innerHTML=t.map(x=>`<div class="movement"><div class="mleft"><button class="secondary" style="padding:6px 9px" onclick="doneTask('${x.id}')">✓</button><div><div class="mname">${esc(x.title)}</div><div class="meta">${x.date?fmt(x.date):'Sin fecha'}</div></div></div></div>`).join('')||'<div class="empty">No tienes pendientes.</div>'}
function doneTask(id){let x=data.tasks.find(x=>x.id===id);if(x)x.done=true;save()}
function renderCalendar(){let y=cal.getFullYear(),m=cal.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate();document.getElementById('calTitle').textContent=new Date(y,m,1).toLocaleDateString('es-BO',{month:'long',year:'numeric'});let out=['L','M','X','J','V','S','D'].map(x=>`<div class="weekday">${x}</div>`).join('');for(let i=0;i<first;i++)out+='<div></div>';let today=new Date();for(let d=1;d<=days;d++){let ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,has=data.payments.some(x=>x.date===ds&&x.status!=='paid')||data.tasks.some(x=>x.date===ds),isToday=today.getFullYear()===y&&today.getMonth()===m&&today.getDate()===d;out+=`<div class="day ${isToday?'today':''}"><b>${d}</b>${has?'<div class="dot"></div>':''}</div>`}document.getElementById('calendar').innerHTML=out}
function changeMonth(n){cal.setMonth(cal.getMonth()+n);renderCalendar()}
function renderChart(){let el=document.getElementById('chartBars'),days=['1','5','10','15','20','25','31'];el.innerHTML=days.map((d,i)=>`<div class="barpair" style="position:relative"><div class="bar in" style="height:${data.movements.length?Math.max(3,(i+1)*3):2}%"></div><div class="bar out" style="height:${data.movements.length?Math.max(3,(7-i)*2):2}%"></div><span class="barlabel" style="left:50%">${d}</span></div>`).join('')}
function renderWeekly(){let t=totals(),rows=['Lun 11','Mar 12','Mié 13','Jue 14'].map(x=>`<div class="weekrow"><span class="weekday">${x}</span><span>${money(0)} · 0 movimientos</span><span class="income">↗ 0</span><span class="expense">↓ 0</span></div>`).join('');document.getElementById('weekly').innerHTML=rows;document.getElementById('reportWeekly').innerHTML=`<div class="settingrow"><div><b>Ingresos</b><span>Total registrado</span></div><strong class="income">${money(t.i)}</strong></div><div class="settingrow"><div><b>Egresos</b><span>Total registrado</span></div><strong class="expense">${money(t.e)}</strong></div><div class="settingrow"><div><b>Resultado</b><span>Ingresos − egresos</span></div><strong>${money(t.b)}</strong></div>`}
const titles={home:['Inicio','Resumen de tus finanzas y agenda'],finance:['Finanzas','Control de ingresos y egresos'],payments:['Pagos','Obligaciones y vencimientos'],agenda:['Agenda','Calendario y pendientes'],reports:['Reportes','Resumen de actividad'],goals:['Metas','Objetivos personales'],contacts:['Contactos','Personas importantes'],notes:['Notas','Ideas y recordatorios'],documents:['Documentos','Archivos personales'],settings:['Configuración','Personaliza Mi Agenda']};
function show(id,btn){let target=document.getElementById(id);if(!target)return;document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));target.classList.add('active');document.querySelectorAll('.sidebtn[data-screen],.mobilebar button').forEach(x=>x.classList.remove('active'));document.querySelectorAll(`[data-screen="${id}"]`).forEach(x=>x.classList.add('active'));document.getElementById('searchInput').value='';window.scrollTo({top:0,behavior:'smooth'})}
function openModal(type){let titles={income:'Nuevo ingreso',expense:'Nuevo egreso',payment:'Nuevo pago pendiente',task:'Nuevo pendiente'},isMov=type==='income'||type==='expense';document.getElementById('modalContent').innerHTML=`<h2>${titles[type]}</h2><form class="form" onsubmit="submitForm(event,'${type}')"><label>Concepto<input id="fTitle" required placeholder="Ej. Consulta, Internet, préstamo..."></label>${isMov||type==='payment'?'<label>Monto<input id="fAmount" type="number" min="0" step="0.01" required placeholder="0"></label>':''}<label>Fecha<input id="fDate" type="date" value="${new Date().toISOString().slice(0,10)}"></label>${isMov||type==='payment'?'<label>Categoría<select id="fCat"><option>General</option><option>Trabajo</option><option>Hogar</option><option>Servicios</option><option>Transporte</option><option>Alimentación</option><option>Compras</option><option>Otros</option></select></label>':''}<div class="formactions"><button class="secondary" type="button" onclick="closeModal()">Cancelar</button><button class="primary" type="submit">Guardar</button></div></form>`;document.getElementById('modal').classList.add('show')}
function submitForm(e,type){e.preventDefault();let title=document.getElementById('fTitle').value.trim(),date=document.getElementById('fDate').value||new Date().toISOString().slice(0,10);if(type==='income'||type==='expense')data.movements.push({id:crypto.randomUUID(),type,title,amount:+document.getElementById('fAmount').value,category:document.getElementById('fCat').value,date});else if(type==='payment')data.payments.push({id:crypto.randomUUID(),title,amount:+document.getElementById('fAmount').value,category:document.getElementById('fCat').value,date,status:'pending'});else data.tasks.push({id:crypto.randomUUID(),title,date,done:false});closeModal();save()}
function closeModal(){document.getElementById('modal').classList.remove('show')}function toast(s){let t=document.getElementById('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function applyTheme(dark){document.documentElement.classList.toggle('dark',dark);document.getElementById('themeSwitch').classList.toggle('on',dark);document.getElementById('themeIcon').textContent=dark?'☀':'☾';document.getElementById('lightBtn').classList.toggle('active',!dark);document.getElementById('darkBtn').classList.toggle('active',dark);localStorage.setItem('mi-agenda-theme',dark?'dark':'light')}
function toggleTheme(){applyTheme(!document.documentElement.classList.contains('dark'))}
function clearData(){if(confirm('¿Restablecer todos los datos locales de Mi Agenda?')){data={movements:[],payments:[],tasks:[]};save()}}
function filterSearch(q){if(!q.trim()){renderMovements();return}let term=q.toLowerCase();document.querySelectorAll('.mname').forEach(el=>{el.closest('.movement').style.display=el.textContent.toLowerCase().includes(term)?'flex':'none'})}
function toggleMobileMenu(){toast('Usa la barra inferior para navegar en móvil')}
applyTheme(localStorage.getItem('mi-agenda-theme')==='dark');render();