const KEY='mi-agenda-v1';let data=JSON.parse(localStorage.getItem(KEY)||'{"movements":[],"payments":[],"tasks":[]}');let cal=new Date();
const money=n=>'Bs '+Number(n||0).toLocaleString('es-BO',{minimumFractionDigits:0,maximumFractionDigits:2});const iso=d=>d.toISOString().slice(0,10);const fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('es-BO',{day:'2-digit',month:'short',year:'numeric'});const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem(KEY,JSON.stringify(data));render();toast('Guardado correctamente')}function totals(){let i=data.movements.filter(x=>x.type==='income').reduce((a,x)=>a+ +x.amount,0),e=data.movements.filter(x=>x.type==='expense').reduce((a,x)=>a+ +x.amount,0);return{i,e,b:i-e}}
function render(){const t=totals(),now=new Date(),h=now.getHours();document.getElementById('balance').textContent=money(t.b);document.getElementById('income').textContent=money(t.i);document.getElementById('expense').textContent=money(t.e);document.getElementById('financeBalance').textContent=money(t.b);document.getElementById('financeIncome').textContent=money(t.i);document.getElementById('financeExpense').textContent=money(t.e);document.getElementById('incomeCount').textContent=data.movements.filter(x=>x.type==='income').length+' ingresos';document.getElementById('expenseCount').textContent=data.movements.filter(x=>x.type==='expense').length+' egresos';let pending=data.payments.filter(x=>x.status!=='paid');document.getElementById('pendingAmount').textContent=money(pending.reduce((a,x)=>a+ +x.amount,0));document.getElementById('pendingCount').textContent=pending.length+' pendientes';document.getElementById('greeting').textContent=(h<12?'¡Buenos días':h<19?'¡Buenas tardes':'¡Buenas noches')+', Jeason! 👋';document.getElementById('todayLabel').textContent=now.toLocaleDateString('es-BO',{weekday:'long',day:'numeric',month:'long',year:'numeric'});renderMovements();renderPayments();renderCalendar();renderTasks();renderChart();renderCategory();renderWeekly();renderEvents()}
function movementItem(x){return `<div class="movement"><div class="mleft"><div class="micon">${x.type==='income'?'↗':'↘'}</div><div><div class="mname">${esc(x.title)}</div><div class="meta">${esc(x.category||'General')} · ${fmt(x.date)}</div></div></div><div class="amount ${x.type==='income'?'income':'expense'}">${x.type==='income'?'+':'−'}${money(x.amount)}</div></div>`}
function renderMovements(){let s=[...data.movements].sort((a,b)=>b.date.localeCompare(a.date));document.getElementById('recent').innerHTML=s.slice(0,5).map(movementItem).join('')||'<div class="empty">No hay movimientos registrados.</div>';document.getElementById('allMovements').innerHTML=s.map(movementItem).join('')||'<div class="empty">Registra tu primer movimiento.</div>'}
function paymentItem(p){return `<div class="movement"><div class="mleft"><div class="micon">◷</div><div><div class="mname">${esc(p.title)}</div><div class="meta">${fmt(p.date)} · ${esc(p.category||'General')}</div></div></div><div style="text-align:right"><div class="amount" style="color:#b7791f">${money(p.amount)}</div><button class="link" onclick="pay('${p.id}')">${p.status==='paid'?'Pagado':'Marcar pagado'}</button></div></div>`}
function renderPayments(){let p=[...data.payments].sort((a,b)=>a.date.localeCompare(b.date)),pending=p.filter(x=>x.status!=='paid');document.getElementById('paymentsList').innerHTML=p.map(paymentItem).join('')||'<div class="card empty">No tienes pagos registrados.</div>';document.getElementById('homePayments').innerHTML=pending.slice(0,3).map(paymentItem).join('')||'<div class="empty">No hay pagos pendientes.</div>'}
function pay(id){let p=data.payments.find(x=>x.id===id);if(!p||p.status==='paid')return;p.status='paid';data.movements.push({id:crypto.randomUUID(),type:'expense',title:p.title,amount:p.amount,category:p.category,date:iso(new Date())});save()}
function renderTasks(){let t=data.tasks.filter(x=>!x.done).sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'));document.getElementById('tasks').innerHTML=t.map(x=>`<div class="movement"><div class="mleft"><button class="secondary" style="padding:6px 9px" onclick="doneTask('${x.id}')">✓</button><div><div class="mname">${esc(x.title)}</div><div class="meta">${x.date?fmt(x.date):'Sin fecha'}</div></div></div></div>`).join('')||'<div class="empty">No tienes pendientes.</div>'}
function doneTask(id){let x=data.tasks.find(x=>x.id===id);if(x)x.done=true;save()}
function renderCalendar(){let y=cal.getFullYear(),m=cal.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate();document.getElementById('calTitle').textContent=new Date(y,m,1).toLocaleDateString('es-BO',{month:'long',year:'numeric'});let out=['L','M','X','J','V','S','D'].map(x=>`<div class="weekday">${x}</div>`).join('');for(let i=0;i<first;i++)out+='<div></div>';let today=iso(new Date());for(let d=1;d<=days;d++){let ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,has=data.payments.some(x=>x.date===ds&&x.status!=='paid')||data.tasks.some(x=>x.date===ds&&!x.done),isToday=today===ds;out+=`<div class="day ${isToday?'today':''}"><b>${d}</b>${has?'<div class="dot"></div>':''}</div>`}document.getElementById('calendar').innerHTML=out}
function changeMonth(n){cal.setMonth(cal.getMonth()+n);renderCalendar()}
function renderChart(){let el=document.getElementById('chartBars'),now=new Date(),y=now.getFullYear(),m=now.getMonth(),days=new Date(y,m+1,0).getDate(),points=[1,5,10,15,20,25,days],max=1;let vals=points.map(day=>{let end=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;let ins=data.movements.filter(x=>x.type==='income'&&x.date<=end).reduce((a,x)=>a+ +x.amount,0);let out=data.movements.filter(x=>x.type==='expense'&&x.date<=end).reduce((a,x)=>a+ +x.amount,0);max=Math.max(max,ins,out);return[ins,out]});el.innerHTML=vals.map((v,i)=>`<div class="barpair" style="position:relative"><div class="bar in" style="height:${v[0]?Math.max(3,v[0]/max*92):2}%"></div><div class="bar out" style="height:${v[1]?Math.max(3,v[1]/max*92):2}%"></div><span class="barlabel" style="left:50%">${points[i]}</span></div>`).join('')}
function renderCategory(){let cats={};data.movements.forEach(x=>cats[x.category||'General']=(cats[x.category||'General']||0)+Number(x.amount));let total=Object.values(cats).reduce((a,x)=>a+x,0);document.getElementById('categoryTotal').textContent=money(total);let el=document.querySelector('.donut');if(!total){el.style.background='conic-gradient(var(--soft) 0 100%)';return}let palette=['#0f8b78','#3b82f6','#8b5cf6','#f59e0b','#ef5350','#11966a'];let start=0,parts=Object.entries(cats).map(([k,v],i)=>{let end=start+v/total*100,p=`${palette[i%palette.length]} ${start}% ${end}%`;start=end;return p});el.style.background=`conic-gradient(${parts.join(',')})`;document.querySelector('.donutcenter span').textContent=Object.keys(cats).length+' categorías'}
function renderWeekly(){let now=new Date(),monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));let rows=[];for(let i=0;i<4;i++){let d=new Date(monday);d.setDate(monday.getDate()+i);let ds=iso(d),ins=data.movements.filter(x=>x.date===ds&&x.type==='income').reduce((a,x)=>a+ +x.amount,0),out=data.movements.filter(x=>x.date===ds&&x.type==='expense').reduce((a,x)=>a+ +x.amount,0),count=data.movements.filter(x=>x.date===ds).length;rows.push(`<div class="weekrow"><span class="weekday">${d.toLocaleDateString('es-BO',{weekday:'short',day:'2-digit'})}</span><span>${money(ins-out)} · ${count} movimientos</span><span class="income">↗ ${money(ins).replace('Bs ','')}</span><span class="expense">↓ ${money(out).replace('Bs ','')}</span></div>`)}document.getElementById('weekly').innerHTML=rows.join('');document.getElementById('reportWeekly').innerHTML=`<div class="settingrow"><div><b>Ingresos</b><span>Total registrado</span></div><strong class="income">${money(totals().i)}</strong></div><div class="settingrow"><div><b>Egresos</b><span>Total registrado</span></div><strong class="expense">${money(totals().e)}</strong></div><div class="settingrow"><div><b>Resultado</b><span>Ingresos − egresos</span></div><strong>${money(totals().b)}</strong></div>`}
function renderEvents(){let future=data.tasks.filter(x=>!x.done&&x.date&&x.date>=iso(new Date())).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,3),box=document.querySelector('.event .empty');if(!future.length){box.innerHTML='<b>No hay eventos próximos</b><br><span>Crea eventos en tu agenda para verlos aquí.</span>';return}box.innerHTML=future.map(x=>`<div style="padding:5px 0"><b>${esc(x.title)}</b><br><span>${fmt(x.date)}</span></div>`).join('')}
const titles={home:['Inicio','Resumen de tus finanzas y agenda'],finance:['Finanzas','Control de ingresos y egresos'],payments:['Pagos','Obligaciones y vencimientos'],agenda:['Agenda','Calendario y pendientes'],reports:['Reportes','Resumen de actividad'],goals:['Metas','Objetivos personales'],contacts:['Contactos','Personas importantes'],notes:['Notas','Ideas y recordatorios'],documents:['Documentos','Archivos personales'],settings:['Configuración','Personaliza Mi Agenda']};
function show(id,btn){let target=document.getElementById(id);if(!target)return;document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));target.classList.add('active');document.querySelectorAll('.sidebtn[data-screen],.mobilebar button').forEach(x=>x.classList.remove('active'));document.querySelectorAll(`[data-screen="${id}"]`).forEach(x=>x.classList.add('active'));document.getElementById('searchInput').value='';window.scrollTo({top:0,behavior:'smooth'})}
function openModal(type){let titles={income:'Nuevo ingreso',expense:'Nuevo egreso',payment:'Nuevo pago pendiente',task:'Nuevo pendiente'},isMov=type==='income'||type==='expense';document.getElementById('modalContent').innerHTML=`<h2>${titles[type]}</h2><form class="form" onsubmit="submitForm(event,'${type}')"><label>Concepto<input id="fTitle" required placeholder="Ej. Consulta, Internet, préstamo..."></label>${isMov||type==='payment'?'<label>Monto<input id="fAmount" type="number" min="0" step="0.01" required placeholder="0"></label>':''}<label>Fecha<input id="fDate" type="date" value="${iso(new Date())}"></label>${isMov||type==='payment'?'<label>Categoría<select id="fCat"><option>General</option><option>Trabajo</option><option>Hogar</option><option>Servicios</option><option>Transporte</option><option>Alimentación</option><option>Compras</option><option>Otros</option></select></label>':''}<div class="formactions"><button class="secondary" type="button" onclick="closeModal()">Cancelar</button><button class="primary" type="submit">Guardar</button></div></form>`;document.getElementById('modal').classList.add('show')}
function submitForm(e,type){e.preventDefault();let title=document.getElementById('fTitle').value.trim(),date=document.getElementById('fDate').value||iso(new Date());if(type==='income'||type==='expense')data.movements.push({id:crypto.randomUUID(),type,title,amount:+document.getElementById('fAmount').value,category:document.getElementById('fCat').value,date});else if(type==='payment')data.payments.push({id:crypto.randomUUID(),title,amount:+document.getElementById('fAmount').value,category:document.getElementById('fCat').value,date,status:'pending'});else data.tasks.push({id:crypto.randomUUID(),title,date,done:false});closeModal();save()}
function closeModal(){document.getElementById('modal').classList.remove('show')}function toast(s){let t=document.getElementById('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function applyTheme(dark){document.documentElement.classList.toggle('dark',dark);document.getElementById('themeSwitch').classList.toggle('on',dark);document.getElementById('themeIcon').textContent=dark?'☀':'☾';document.getElementById('lightBtn').classList.toggle('active',!dark);document.getElementById('darkBtn').classList.toggle('active',dark);localStorage.setItem('mi-agenda-theme',dark?'dark':'light')}
function toggleTheme(){applyTheme(!document.documentElement.classList.contains('dark'))}function clearData(){if(confirm('¿Restablecer todos los datos locales de Mi Agenda?')){data={movements:[],payments:[],tasks:[]};save()}}
function filterSearch(q){let term=q.trim().toLowerCase();document.querySelectorAll('.mname').forEach(el=>el.closest('.movement').style.display=!term||el.textContent.toLowerCase().includes(term)?'flex':'none')}
function toggleMobileMenu(){toast('Usa la barra inferior para navegar en móvil')}
applyTheme(localStorage.getItem('mi-agenda-theme')==='dark');render();