(()=>{'use strict';
const KEY='mi-agenda-planner-v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>'Bs '+Number(n||0).toLocaleString('es-BO',{maximumFractionDigits:2});
const fmt=d=>d?new Date(d+'T12:00:00').toLocaleDateString('es-BO',{day:'2-digit',month:'short',year:'numeric'}):'Sin fecha';
const uid=()=> 'ar'+Date.now().toString(36)+Math.random().toString(36).slice(2,6);
function db(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');x.autoRecords=Array.isArray(x.autoRecords)?x.autoRecords:[];return x}catch{return{autoRecords:[]}}}
function save(x){localStorage.setItem(KEY,JSON.stringify(x));window.toast?.('Guardado correctamente')}
function modal(html){let m=document.getElementById('uxModal');if(!m){m=document.createElement('div');m.id='uxModal';m.className='ux-modal';m.innerHTML='<div class="ux-sheet" id="uxSheet"></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('show')})}document.getElementById('uxSheet').innerHTML=html;m.classList.add('show')}
window.closeUxModal=window.closeUxModal||(()=>document.getElementById('uxModal')?.classList.remove('show'));
function row(r){return `<article class="auto-record" onclick="editAutoRecordSimple('${r.id}')"><div><b>${esc(r.title||'Mantenimiento')}</b><div class="meta">${fmt(r.date)}</div>${r.notes?`<div class="planner-muted">${esc(r.notes)}</div>`:''}</div><strong>${money(r.cost)}</strong></article>`}
window.renderAutoSimple=function(){const root=document.getElementById('autoApp');if(!root)return;const x=db(),records=x.autoRecords,total=records.reduce((s,r)=>s+Number(r.cost||0),0);root.innerHTML=`<div class="ux-head"><div><h2>Auto</h2><p>Registra de forma rápida los mantenimientos y gastos de tu vehículo.</p></div><div class="ux-actions"><button class="primary" onclick="newAutoMaintenance()">＋ Nuevo mantenimiento</button></div></div><div class="report-metrics auto-simple-metrics"><div class="metric"><small>Gasto total</small><strong>${money(total)}</strong></div><div class="metric"><small>Mantenimientos</small><strong>${records.length}</strong></div></div><div class="card auto-simple-history"><div class="cardhead"><h3>Historial de mantenimiento</h3></div><div>${records.map(row).join('')||'<div class="ux-empty">Todavía no registraste mantenimientos. Pulsa “Nuevo mantenimiento” para comenzar.</div>'}</div></div>`};
function form(id=''){const x=db(),r=x.autoRecords.find(v=>v.id===id)||{title:'',cost:0,date:new Date().toISOString().slice(0,10),notes:''};modal(`<h2>${id?'Editar mantenimiento':'Nuevo mantenimiento'}</h2><form class="ux-form" id="autoSimpleForm"><label>Mantenimiento<input id="asTitle" required value="${esc(r.title)}" placeholder="Ej. Cambio de aceite, frenos, llantas..."></label><label>Costo<input id="asCost" type="number" min="0" step="0.01" value="${r.cost||''}" placeholder="0"></label><label>Fecha<input id="asDate" type="date" value="${r.date||''}"></label><label>Nota <small>(opcional)</small><textarea id="asNotes" placeholder="Algún detalle que quieras recordar">${esc(r.notes||'')}</textarea></label><div class="ux-form-actions">${id?`<button type="button" class="secondary" onclick="deleteAutoMaintenance('${id}')">Eliminar</button>`:'<button type="button" class="secondary" onclick="closeUxModal()">Cancelar</button>'}<button class="primary">Guardar</button></div></form>`);document.getElementById('autoSimpleForm').onsubmit=e=>{e.preventDefault();r.title=document.getElementById('asTitle').value.trim();r.cost=Number(document.getElementById('asCost').value||0);r.date=document.getElementById('asDate').value;r.notes=document.getElementById('asNotes').value.trim();if(!id){r.id=uid();x.autoRecords.unshift(r)}save(x);closeUxModal();renderAutoSimple()}}
window.newAutoMaintenance=()=>form();window.editAutoRecordSimple=id=>form(id);window.deleteAutoMaintenance=id=>{if(!confirm('¿Eliminar este mantenimiento?'))return;const x=db();x.autoRecords=x.autoRecords.filter(r=>r.id!==id);save(x);closeUxModal();renderAutoSimple()};
function loadTripVisualPatch(){if(!document.querySelector('link[data-trip-collage]')){const l=document.createElement('link');l.rel='stylesheet';l.href='trip-collage-budget.css?v=1';l.dataset.tripCollage='1';document.head.appendChild(l)}if(!document.querySelector('script[data-trip-collage]')){const s=document.createElement('script');s.src='trip-collage-budget.js?v=1';s.defer=true;s.dataset.tripCollage='1';document.body.appendChild(s)}}
function activate(){loadTripVisualPatch();renderAutoSimple();document.querySelectorAll('[data-screen="auto"]').forEach(b=>b.addEventListener('click',()=>setTimeout(renderAutoSimple,0)))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(activate,20));else setTimeout(activate,20);
})();