(()=>{
  const STORAGE='mi-agenda-loans-v1';
  const load=()=>{try{const x=JSON.parse(localStorage.getItem(STORAGE)||'[]');return Array.isArray(x)?x:[]}catch{return[]}};
  let loans=load();
  const save=()=>localStorage.setItem(STORAGE,JSON.stringify(loans));
  const money=n=>'Bs '+Number(n||0).toLocaleString('es-BO',{minimumFractionDigits:0,maximumFractionDigits:2});
  const iso=d=>{const x=d instanceof Date?d:new Date(d);return x.getFullYear()+'-'+String(x.getMonth()+1).padStart(2,'0')+'-'+String(x.getDate()).padStart(2,'0')};
  const fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('es-BO',{day:'2-digit',month:'short',year:'numeric'});
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const monthsBetween=(a,b)=>{const x=new Date(a+'T12:00:00'),y=new Date(b+'T12:00:00');if(y<=x)return 0;return Math.max(0,(y.getFullYear()-x.getFullYear())*12+(y.getMonth()-x.getMonth())+(y.getDate()>=x.getDate()?0:0));};
  const calc=l=>{const scheduledInterest=Number(l.principal)*Number(l.rate||0)/100*monthsBetween(l.startDate,l.dueDate);const paidInterest=(l.payments||[]).reduce((s,p)=>s+Number(p.interest||0),0);const paidCapital=(l.payments||[]).reduce((s,p)=>s+Number(p.capital||0),0);const capital=Math.max(0,Number(l.principal)-paidCapital);const interest=Math.max(0,scheduledInterest-paidInterest);const total=Math.max(0,capital+interest);const today=iso(new Date());let status=capital<=0?'paid':today>l.dueDate?'overdue':'active';return{scheduledInterest,paidInterest,paidCapital,capital,interest,total,status}};
  const badge=s=>s==='paid'?'<span class="loan-badge paid">Pagado</span>':s==='overdue'?'<span class="loan-badge overdue">Vencido</span>':'<span class="loan-badge active">Vigente</span>';
  function inject(){
    const css=document.createElement('link');css.rel='stylesheet';css.href='loans-module.css?v=1';document.head.appendChild(css);
    const settings=document.querySelector('[data-screen="settings"]');
    if(settings&&!document.querySelector('[data-screen="loans"]')){const b=document.createElement('button');b.className='navbtn';b.dataset.screen='loans';b.innerHTML='<span class="navicon">$</span>Préstamos';b.addEventListener('click',()=>window.nav('loans'));settings.parentNode.insertBefore(b,settings);}
    if(document.getElementById('loans'))return;
    const section=document.createElement('div');section.id='loans';section.className='screen';section.innerHTML=`<div class="pagehead"><div><h2>Préstamos</h2><p>Control de capital, intereses, vencimientos y pagos parciales.</p></div><button class="primary" id="newLoan">＋ Nuevo préstamo</button></div>
      <div class="loan-metrics"><div class="metric"><small>Capital prestado</small><strong id="loanCapital">Bs 0</strong></div><div class="metric"><small>Interés pendiente</small><strong id="loanInterest">Bs 0</strong></div><div class="metric"><small>Total por cobrar</small><strong id="loanTotal">Bs 0</strong></div><div class="metric"><small>Vencidos</small><strong id="loanOverdue">0</strong></div></div>
      <div class="card loan-list-card"><div class="cardhead"><h3>Mis préstamos</h3><div class="loan-filters"><button class="secondary loan-filter active" data-filter="all">Todos</button><button class="secondary loan-filter" data-filter="active">Vigentes</button><button class="secondary loan-filter" data-filter="overdue">Vencidos</button><button class="secondary loan-filter" data-filter="paid">Pagados</button></div></div><div id="loanList"></div></div>`;
    document.querySelector('.content').appendChild(section);
    const modal=document.createElement('div');modal.id='loanModal';modal.className='modal';modal.innerHTML='<div class="sheet loan-sheet"><div id="loanFormHost"></div></div>';document.body.appendChild(modal);
    document.getElementById('newLoan').onclick=()=>openLoan();
    document.querySelectorAll('.loan-filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.loan-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});
    render();
  }
  function openLoan(existing){
    const l=existing||{id:'l'+Date.now().toString(36),person:'',phone:'',principal:'',startDate:iso(new Date()),dueDate:iso(new Date()),rate:'',notes:'',payments:[]};
    const host=document.getElementById('loanFormHost');host.innerHTML=`<h2>${existing?'Editar préstamo':'Nuevo préstamo'}</h2><form class="form loan-form" id="loanForm"><div class="loan-form-grid"><label>Persona / prestatario<input id="lpPerson" required value="${esc(l.person)}" placeholder="Nombre completo"></label><label>Teléfono <span class="optional">opcional</span><input id="lpPhone" value="${esc(l.phone||'')}" placeholder="70000000"></label><label>Monto prestado<input id="lpPrincipal" type="number" min="0" step="0.01" required value="${l.principal||''}"></label><label>Interés mensual (%) <span class="optional">opcional</span><input id="lpRate" type="number" min="0" step="0.01" value="${l.rate||''}" placeholder="Ej. 5"></label><label>Fecha del préstamo<input id="lpStart" type="date" required value="${l.startDate}"></label><label>Fecha límite de pago<input id="lpDue" type="date" required value="${l.dueDate}"></label></div><label>Observaciones <span class="optional">opcional</span><textarea id="lpNotes" rows="3" placeholder="Condiciones o notas del préstamo...">${esc(l.notes||'')}</textarea><div class="loan-preview" id="loanPreview"></div><div class="formactions"><button type="button" class="secondary" onclick="window.closeLoanModal()">Cancelar</button><button class="primary">Guardar préstamo</button></div></form>`;
    const preview=()=>{const p=Number(document.getElementById('lpPrincipal').value||0),r=Number(document.getElementById('lpRate').value||0),s=document.getElementById('lpStart').value,d=document.getElementById('lpDue').value,m=s&&d?monthsBetween(s,d):0;document.getElementById('loanPreview').innerHTML=`<b>Vista previa</b><span>Interés mensual: ${money(p*r/100)}</span><span>Interés estimado hasta vencimiento: ${money(p*r/100*m)}</span><span>Total estimado: ${money(p+p*r/100*m)}</span>`};
    ['lpPrincipal','lpRate','lpStart','lpDue'].forEach(id=>document.getElementById(id).addEventListener('input',preview));preview();document.getElementById('loanModal').classList.add('show');
    document.getElementById('loanForm').onsubmit=e=>{e.preventDefault();l.person=document.getElementById('lpPerson').value.trim();l.phone=document.getElementById('lpPhone').value.trim();l.principal=Number(document.getElementById('lpPrincipal').value);l.rate=Number(document.getElementById('lpRate').value||0);l.startDate=document.getElementById('lpStart').value;l.dueDate=document.getElementById('lpDue').value;l.notes=document.getElementById('lpNotes').value.trim();if(!existing)loans.unshift(l);save();closeLoanModal();render()};
  }
  function closeLoanModal(){document.getElementById('loanModal').classList.remove('show')}
  function openPayment(id){const l=loans.find(x=>x.id===id);if(!l)return;const host=document.getElementById('loanFormHost');const c=calc(l);host.innerHTML=`<h2>Registrar pago</h2><div class="loan-payment-summary"><span>Saldo de capital: <b>${money(c.capital)}</b></span><span>Interés pendiente: <b>${money(c.interest)}</b></span></div><form class="form" id="paymentForm"><label>Fecha del pago<input id="payDate" type="date" value="${iso(new Date())}" required></label><label>Tipo de pago<select id="payType"><option value="interest">Solo interés</option><option value="capital">Solo capital</option><option value="mixed">Interés + capital</option></select></label><label>Monto de interés<input id="payInterest" type="number" min="0" step="0.01" value="${c.interest?Math.min(c.interest,Number(l.principal)*Number(l.rate||0)/100):0}"></label><label>Monto a capital<input id="payCapital" type="number" min="0" step="0.01" value="0"></label><label>Nota <span class="optional">opcional</span><input id="payNote" placeholder="Ej. Pago correspondiente a agosto"></label><div class="formactions"><button type="button" class="secondary" onclick="window.closeLoanModal()">Cancelar</button><button class="primary">Registrar pago</button></div></form>`;
    const type=document.getElementById('payType'),pi=document.getElementById('payInterest'),pc=document.getElementById('payCapital');const sync=()=>{if(type.value==='interest'){pi.disabled=false;pc.value=0;pc.disabled=true}else if(type.value==='capital'){pi.value=0;pi.disabled=true;pc.disabled=false}else{pi.disabled=false;pc.disabled=false}};type.onchange=sync;sync();document.getElementById('loanModal').classList.add('show');document.getElementById('paymentForm').onsubmit=e=>{e.preventDefault();const interest=Number(pi.value||0),capital=Number(pc.value||0);if(interest+capital<=0)return;if(interest>c.interest||capital>c.capital){alert('El pago supera el saldo pendiente.');return}l.payments=l.payments||[];l.payments.push({id:'p'+Date.now().toString(36),date:document.getElementById('payDate').value,interest,capital,note:document.getElementById('payNote').value.trim()});save();closeLoanModal();render()};
  }
  function editLoan(id){const l=loans.find(x=>x.id===id);if(l)openLoan(l)}
  function render(filter='all'){
    const list=document.getElementById('loanList');if(!list)return;let capital=0,interest=0,total=0,overdue=0;loans.forEach(l=>{const c=calc(l);if(c.status!=='paid'){capital+=c.capital;interest+=c.interest;total+=c.total}if(c.status==='overdue')overdue++});document.getElementById('loanCapital').textContent=money(capital);document.getElementById('loanInterest').textContent=money(interest);document.getElementById('loanTotal').textContent=money(total);document.getElementById('loanOverdue').textContent=overdue;
    const shown=loans.filter(l=>filter==='all'||calc(l).status===filter);if(!shown.length){list.innerHTML='<div class="empty loan-empty">No hay préstamos en esta categoría.<br>Registra el primero para comenzar.</div>';return}
    list.innerHTML=shown.map(l=>{const c=calc(l),next=l.payments&&l.payments.length?l.payments[l.payments.length-1].date:l.startDate;return `<article class="loan-card"><div class="loan-card-top"><div><div class="loan-person">${esc(l.person)}</div><div class="meta">${l.phone?esc(l.phone)+' · ':''}Prestado ${fmt(l.startDate)}</div></div>${badge(c.status)}</div><div class="loan-grid"><div><small>Capital original</small><b>${money(l.principal)}</b></div><div><small>Capital pendiente</small><b>${money(c.capital)}</b></div><div><small>Interés pendiente</small><b>${money(c.interest)}</b></div><div><small>Vence</small><b>${fmt(l.dueDate)}</b></div></div><div class="loan-card-footer"><span>${l.rate?esc(String(l.rate))+'% mensual · ':''}${c.paidInterest?money(c.paidInterest)+' interés pagado · ':''}${c.paidCapital?money(c.paidCapital)+' capital pagado':''}</span><div><button class="secondary loan-small" onclick="window.editLoan('${l.id}')">Editar</button><button class="secondary loan-small" onclick="window.openLoanPayments('${l.id}')">Historial</button>${c.status!=='paid'?'<button class="primary loan-small" onclick="window.openLoanPayment(\''+l.id+'\')">＋ Registrar pago</button>':''}</div></div></article>`}).join('');
  }
  function history(id){const l=loans.find(x=>x.id===id);if(!l)return;const c=calc(l);document.getElementById('loanFormHost').innerHTML=`<h2>Historial · ${esc(l.person)}</h2><div class="loan-payment-summary"><span>Capital pendiente: <b>${money(c.capital)}</b></span><span>Interés pendiente: <b>${money(c.interest)}</b></span></div><div class="loan-history">${(l.payments||[]).map(p=>`<div class="item"><div><b>${p.interest&&p.capital?'Pago mixto':p.interest?'Interés':'Capital'}</b><div class="meta">${fmt(p.date)}${p.note?' · '+esc(p.note):''}</div></div><strong>${money(Number(p.interest||0)+Number(p.capital||0))}</strong></div>`).join('')||'<div class="empty">Todavía no hay pagos registrados.</div>'}</div><div class="formactions"><button class="secondary" onclick="window.closeLoanModal()">Cerrar</button></div>`;document.getElementById('loanModal').classList.add('show')}
  window.closeLoanModal=closeLoanModal;window.openLoanPayment=openPayment;window.openLoanPayments=history;window.editLoan=editLoan;
  document.addEventListener('DOMContentLoaded',inject);
})();
