(()=>{'use strict';
const KEY='mi-agenda-planner-v1';
const seed=()=>({notes:[],pending:[],goalCategories:[{id:'gc-travel',name:'Viajes'},{id:'gc-places',name:'Lugares por conocer'},{id:'gc-projects',name:'Proyectos personales'}],goals:[],autoCategories:[{id:'ac-maint',name:'Mantenimiento'},{id:'ac-oil',name:'Cambio de aceite'},{id:'ac-controls',name:'Próximos controles'},{id:'ac-budget',name:'Presupuesto'}],autoRecords:[]});
let db=load(),activeNote=null,activeGoalCat=db.goalCategories[0]?.id||'',activeAutoCat=db.autoCategories[0]?.id||'';
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&Array.isArray(x.notes)&&Array.isArray(x.pending)&&Array.isArray(x.goals)&&Array.isArray(x.goalCategories)&&Array.isArray(x.autoCategories)&&Array.isArray(x.autoRecords)?x:seed()}catch{return seed()}}
function save(){localStorage.setItem(KEY,JSON.stringify(db));window.toast?.('Guardado correctamente')}
function uid(p='x'){return p+Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function dateISO(d=new Date()){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function fmt(d){return d?new Date(d+'T12:00:00').toLocaleDateString('es-BO',{day:'2-digit',month:'short',year:'numeric'}):'Sin fecha'}
function money(n){return'Bs '+Number(n||0).toLocaleString('es-BO',{maximumFractionDigits:2})}
function modal(html){let m=document.getElementById('plannerModal');if(!m){m=document.createElement('div');m.id='plannerModal';m.className='planner-modal';m.innerHTML='<div class="planner-sheet" id="plannerSheet"></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)closeModal()})}document.getElementById('plannerSheet').innerHTML=html;m.classList.add('show')}
function closeModal(){document.getElementById('plannerModal')?.classList.remove('show')} window.closePlannerModal=closeModal;
function renderAll(){renderNotes();renderPending();renderGoals();renderAuto()}

// NOTAS
function renderNotes(){const root=document.getElementById('notesApp');if(!root)return;if(activeNote&&!db.notes.some(n=>n.id===activeNote))activeNote=null;const current=db.notes.find(n=>n.id===activeNote);root.innerHTML=`<div class="planner-head"><div><h2>Notas</h2><p>Ideas, recordatorios y apuntes organizados.</p></div><div class="planner-actions"><button class="primary" onclick="plannerNewNote()">＋ Nueva nota</button></div></div><div class="notes-layout"><div><input id="noteSearch" placeholder="Buscar notas..." style="width:100%;padding:10px;border:1px solid var(--line);border-radius:10px;background:var(--surface2);color:var(--text);margin-bottom:9px"><div class="notes-list" id="notesList"></div></div><div class="note-editor" id="noteEditor">${current?noteEditor(current):'<div class="planner-empty">Selecciona una nota o crea una nueva.</div>'}</div></div>`;document.getElementById('noteSearch').oninput=e=>renderNoteList(e.target.value);renderNoteList('')}
function renderNoteList(q=''){const list=document.getElementById('notesList');if(!list)return;const rows=[...db.notes].filter(n=>!q||((n.title+' '+n.body).toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''));list.innerHTML=rows.map(n=>`<div class="note-row ${n.id===activeNote?'active':''}" onclick="plannerOpenNote('${n.id}')"><b>${esc(n.title||'Sin título')}</b><span>${new Date(n.updatedAt||n.createdAt).toLocaleString('es-BO',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</span><span>${esc((n.body||'').slice(0,70))}</span></div>`).join('')||'<div class="planner-empty">No hay notas.</div>'}
function noteEditor(n){return`<input id="noteTitle" value="${esc(n.title)}" placeholder="Título de la nota"><textarea id="noteBody" placeholder="Escribe aquí...">${esc(n.body)}</textarea><div class="note-toolbar"><span class="planner-muted">Última edición: ${new Date(n.updatedAt||n.createdAt).toLocaleString('es-BO')}</span><div class="planner-actions"><button class="secondary" onclick="plannerDeleteNote('${n.id}')">Eliminar</button><button class="primary" onclick="plannerSaveNote('${n.id}')">Guardar</button></div></div>`}
window.plannerNewNote=()=>{const n={id:uid('n'),title:'Nueva nota',body:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};db.notes.unshift(n);activeNote=n.id;save();renderNotes()};
window.plannerOpenNote=id=>{activeNote=id;renderNotes()};
window.plannerSaveNote=id=>{const n=db.notes.find(x=>x.id===id);if(!n)return;n.title=document.getElementById('noteTitle').value.trim()||'Sin título';n.body=document.getElementById('noteBody').value;n.updatedAt=new Date().toISOString();save();renderNotes()};
window.plannerDeleteNote=id=>{if(!confirm('¿Eliminar esta nota?'))return;db.notes=db.notes.filter(n=>n.id!==id);activeNote=null;save();renderNotes()};

// PENDIENTES
const statuses=[['todo','Pendiente'],['doing','En proceso'],['done','Completado']];
function renderPending(){const root=document.getElementById('pendingApp');if(!root)return;root.innerHTML=`<div class="planner-head"><div><h2>Pendientes</h2><p>Organiza tareas en un tablero dinámico.</p></div><div class="planner-actions"><button class="primary" onclick="plannerTaskForm()">＋ Nuevo pendiente</button></div></div><div class="kanban">${statuses.map(([id,label])=>`<section class="kanban-col"><h3>${label}<span>${db.pending.filter(t=>t.status===id).length}</span></h3><div class="kanban-drop" data-status="${id}" ondragover="event.preventDefault()" ondrop="plannerDropTask(event,'${id}')">${db.pending.filter(t=>t.status===id).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).map(taskCard).join('')||'<div class="planner-muted">Arrastra tareas aquí</div>'}</div></section>`).join('')}</div>`}
function taskCard(t){return`<article class="task-card" draggable="true" ondragstart="event.dataTransfer.setData('text/plain','${t.id}')" onclick="plannerTaskForm('${t.id}')"><div class="task-title">${esc(t.title)}</div><div class="task-meta"><span class="priority-${t.priority}">${t.priority==='high'?'● Alta':t.priority==='medium'?'● Media':'● Baja'}</span><span>${fmt(t.due)}</span>${t.category?`<span>${esc(t.category)}</span>`:''}</div>${t.description?`<div class="planner-muted" style="margin-top:7px">${esc(t.description.slice(0,100))}</div>`:''}</article>`}
window.plannerDropTask=(e,status)=>{const id=e.dataTransfer.getData('text/plain'),t=db.pending.find(x=>x.id===id);if(t){t.status=status;save();renderPending()}};
window.plannerTaskForm=(id='')=>{const t=db.pending.find(x=>x.id===id)||{title:'',description:'',priority:'medium',due:'',category:'Personal',status:'todo'};modal(`<h2>${id?'Editar pendiente':'Nuevo pendiente'}</h2><form class="planner-form" id="taskForm"><label>Título<input id="ptTitle" required value="${esc(t.title)}"></label><label>Descripción<textarea id="ptDesc">${esc(t.description||'')}</textarea></label><div class="planner-form-grid"><label>Prioridad<select id="ptPriority"><option value="low" ${t.priority==='low'?'selected':''}>Baja</option><option value="medium" ${t.priority==='medium'?'selected':''}>Media</option><option value="high" ${t.priority==='high'?'selected':''}>Alta</option></select></label><label>Fecha límite<input id="ptDue" type="date" value="${t.due||''}"></label></div><div class="planner-form-grid"><label>Categoría<input id="ptCat" value="${esc(t.category||'')}"></label><label>Estado<select id="ptStatus">${statuses.map(([s,l])=>`<option value="${s}" ${t.status===s?'selected':''}>${l}</option>`).join('')}</select></label></div><div class="planner-form-actions">${id?`<button type="button" class="secondary" onclick="plannerDeleteTask('${id}')">Eliminar</button>`:'<button type="button" class="secondary" onclick="closePlannerModal()">Cancelar</button>'}<button class="primary">Guardar</button></div></form>`);document.getElementById('taskForm').onsubmit=e=>{e.preventDefault();const data={title:document.getElementById('ptTitle').value.trim(),description:document.getElementById('ptDesc').value.trim(),priority:document.getElementById('ptPriority').value,due:document.getElementById('ptDue').value,category:document.getElementById('ptCat').value.trim(),status:document.getElementById('ptStatus').value};if(id)Object.assign(t,data);else db.pending.unshift({id:uid('t'),...data,createdAt:new Date().toISOString()});save();closeModal();renderPending()}};
window.plannerDeleteTask=id=>{if(!confirm('¿Eliminar este pendiente?'))return;db.pending=db.pending.filter(t=>t.id!==id);save();closeModal();renderPending()};

// METAS
const goalStatuses=[['idea','Idea'],['planning','Planificando'],['progress','En progreso'],['done','Completado']];
function renderGoals(){const root=document.getElementById('goalsApp');if(!root)return;if(!db.goalCategories.some(c=>c.id===activeGoalCat))activeGoalCat=db.goalCategories[0]?.id||'';const goals=db.goals.filter(g=>g.categoryId===activeGoalCat);root.innerHTML=`<div class="planner-head"><div><h2>Metas</h2><p>Planifica viajes, lugares, proyectos y cualquier objetivo personal.</p></div><div class="planner-actions"><button class="secondary" onclick="plannerGoalCategoryForm()">＋ Categoría</button><button class="primary" onclick="plannerGoalForm()">＋ Nueva meta</button></div></div><div class="board-tabs">${db.goalCategories.map(c=>`<button class="board-tab ${c.id===activeGoalCat?'active':''}" onclick="plannerSelectGoalCat('${c.id}')">${esc(c.name)}</button>`).join('')}</div>${activeGoalCat?`<div class="kanban" style="grid-template-columns:repeat(4,minmax(240px,1fr))">${goalStatuses.map(([s,l])=>`<section class="kanban-col"><h3>${l}<span>${goals.filter(g=>g.status===s).length}</span></h3><div class="kanban-drop" ondragover="event.preventDefault()" ondrop="plannerDropGoal(event,'${s}')">${goals.filter(g=>g.status===s).map(goalCard).join('')||'<div class="planner-muted">Sin metas</div>'}</div></section>`).join('')}</div>`:'<div class="planner-empty">Crea tu primera categoría de metas.</div>'}`}
function goalCard(g){const progress={idea:10,planning:35,progress:70,done:100}[g.status]||0;return`<article class="goal-card" draggable="true" ondragstart="event.dataTransfer.setData('text/plain','${g.id}')" onclick="plannerGoalForm('${g.id}')"><div class="goal-title">${esc(g.title)}</div><div class="goal-meta">${g.targetDate?`<span>${fmt(g.targetDate)}</span>`:''}${g.budget?`<span>${money(g.budget)}</span>`:''}</div><div class="progress"><span style="width:${progress}%"></span></div>${g.notes?`<div class="planner-muted" style="margin-top:7px">${esc(g.notes.slice(0,90))}</div>`:''}${(g.photos||[]).length?`<div class="goal-photos">${g.photos.slice(0,3).map(p=>`<img src="${p}" alt="Foto de meta">`).join('')}</div>`:''}</article>`}
window.plannerSelectGoalCat=id=>{activeGoalCat=id;renderGoals()};
window.plannerDropGoal=(e,status)=>{const id=e.dataTransfer.getData('text/plain'),g=db.goals.find(x=>x.id===id);if(g){g.status=status;save();renderGoals()}};
window.plannerGoalCategoryForm=()=>{modal(`<h2>Nueva categoría de metas</h2><form class="planner-form" id="goalCatForm"><label>Nombre<input id="goalCatName" required placeholder="Ej. Viaje a Europa"></label><div class="planner-form-actions"><button type="button" class="secondary" onclick="closePlannerModal()">Cancelar</button><button class="primary">Crear categoría</button></div></form>`);document.getElementById('goalCatForm').onsubmit=e=>{e.preventDefault();const c={id:uid('gc'),name:document.getElementById('goalCatName').value.trim()};db.goalCategories.push(c);activeGoalCat=c.id;save();closeModal();renderGoals()}};
async function compress(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{let w=im.width,h=im.height,m=1024;if(w>m||h>m){const k=Math.min(m/w,m/h);w*=k;h*=k}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);resolve(c.toDataURL('image/jpeg',.72))};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
window.plannerGoalForm=(id='')=>{const g=db.goals.find(x=>x.id===id)||{title:'',status:'idea',targetDate:'',budget:'',notes:'',photos:[],categoryId:activeGoalCat};modal(`<h2>${id?'Editar meta':'Nueva meta'}</h2><form class="planner-form" id="goalForm"><label>Título<input id="gTitle" required value="${esc(g.title)}" placeholder="Ej. Viaje a Buenos Aires"></label><div class="planner-form-grid"><label>Estado<select id="gStatus">${goalStatuses.map(([s,l])=>`<option value="${s}" ${g.status===s?'selected':''}>${l}</option>`).join('')}</select></label><label>Fecha objetivo<input id="gDate" type="date" value="${g.targetDate||''}"></label></div><label>Presupuesto estimado<input id="gBudget" type="number" min="0" step="0.01" value="${g.budget||''}"></label><label>Notas / planificación<textarea id="gNotes">${esc(g.notes||'')}</textarea></label><label>Fotos <span class="planner-muted">máximo 3</span><input id="gPhotos" type="file" accept="image/*" multiple></label><div class="photo-preview">${(g.photos||[]).map(p=>`<img src="${p}">`).join('')}</div><div class="planner-form-actions">${id?`<button type="button" class="secondary" onclick="plannerDeleteGoal('${id}')">Eliminar</button>`:'<button type="button" class="secondary" onclick="closePlannerModal()">Cancelar</button>'}<button class="primary">Guardar</button></div></form>`);document.getElementById('goalForm').onsubmit=async e=>{e.preventDefault();let photos=[...(g.photos||[])];const files=[...document.getElementById('gPhotos').files].slice(0,Math.max(0,3-photos.length));for(const f of files)try{photos.push(await compress(f))}catch{}const data={title:document.getElementById('gTitle').value.trim(),status:document.getElementById('gStatus').value,targetDate:document.getElementById('gDate').value,budget:Number(document.getElementById('gBudget').value||0),notes:document.getElementById('gNotes').value.trim(),photos,categoryId:activeGoalCat};if(id)Object.assign(g,data);else db.goals.unshift({id:uid('g'),...data,createdAt:new Date().toISOString()});try{save()}catch{alert('No se pudo guardar: el almacenamiento local está lleno. Reduce la cantidad de fotos.');return}closeModal();renderGoals()}};
window.plannerDeleteGoal=id=>{if(!confirm('¿Eliminar esta meta?'))return;db.goals=db.goals.filter(g=>g.id!==id);save();closeModal();renderGoals()};

// AUTO
function autoState(r){const today=dateISO();if(r.status==='done')return'done';if(r.nextDate&&r.nextDate<today)return'overdue';return'upcoming'}
function renderAuto(){const root=document.getElementById('autoApp');if(!root)return;if(!db.autoCategories.some(c=>c.id===activeAutoCat))activeAutoCat=db.autoCategories[0]?.id||'';const records=db.autoRecords.filter(r=>r.categoryId===activeAutoCat),spent=db.autoRecords.filter(r=>r.status==='done').reduce((s,r)=>s+Number(r.cost||0),0),up=db.autoRecords.filter(r=>autoState(r)==='upcoming').length,over=db.autoRecords.filter(r=>autoState(r)==='overdue').length;root.innerHTML=`<div class="planner-head"><div><h2>Auto</h2><p>Mantenimiento, presupuesto, controles y gastos del vehículo.</p></div><div class="planner-actions"><button class="secondary" onclick="plannerAutoCategoryForm()">＋ Categoría</button><button class="primary" onclick="plannerAutoForm()">＋ Nuevo registro</button></div></div><div class="auto-summary"><div class="metric"><small>Gasto registrado</small><strong>${money(spent)}</strong></div><div class="metric"><small>Próximos</small><strong>${up}</strong></div><div class="metric"><small>Vencidos</small><strong>${over}</strong></div><div class="metric"><small>Categorías</small><strong>${db.autoCategories.length}</strong></div></div><div class="auto-category-grid">${db.autoCategories.map(c=>`<div class="auto-cat ${c.id===activeAutoCat?'active':''}" onclick="plannerSelectAutoCat('${c.id}')"><b>${esc(c.name)}</b><span>${db.autoRecords.filter(r=>r.categoryId===c.id).length} registros</span></div>`).join('')}</div><div class="planner-card"><h3>${esc(db.autoCategories.find(c=>c.id===activeAutoCat)?.name||'Registros')}</h3><div>${records.sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(autoRecord).join('')||'<div class="planner-empty" style="margin-top:12px">No hay registros en esta categoría.</div>'}</div></div>`}
function autoRecord(r){const st=autoState(r),label=st==='done'?'Realizado':st==='overdue'?'Vencido':'Próximo';return`<div class="auto-record" onclick="plannerAutoForm('${r.id}')"><div><b>${esc(r.title)}</b><div class="meta">${r.date?fmt(r.date):''}${r.mileage?` · ${Number(r.mileage).toLocaleString('es-BO')} km`:''}${r.nextDate?` · Próximo ${fmt(r.nextDate)}`:''}${r.nextKm?` · ${Number(r.nextKm).toLocaleString('es-BO')} km`:''}</div>${r.notes?`<div class="planner-muted">${esc(r.notes)}</div>`:''}</div><div style="text-align:right"><span class="planner-chip">${label}</span>${r.cost?`<div style="font-size:10px;font-weight:900;margin-top:6px">${money(r.cost)}</div>`:''}</div></div>`}
window.plannerSelectAutoCat=id=>{activeAutoCat=id;renderAuto()};
window.plannerAutoCategoryForm=()=>{modal(`<h2>Nueva categoría del auto</h2><form class="planner-form" id="autoCatForm"><label>Nombre<input id="autoCatName" required placeholder="Ej. Frenos, llantas, seguro"></label><div class="planner-form-actions"><button type="button" class="secondary" onclick="closePlannerModal()">Cancelar</button><button class="primary">Crear categoría</button></div></form>`);document.getElementById('autoCatForm').onsubmit=e=>{e.preventDefault();const c={id:uid('ac'),name:document.getElementById('autoCatName').value.trim()};db.autoCategories.push(c);activeAutoCat=c.id;save();closeModal();renderAuto()}};
window.plannerAutoForm=(id='')=>{const r=db.autoRecords.find(x=>x.id===id)||{title:'',date:dateISO(),mileage:'',cost:'',nextDate:'',nextKm:'',notes:'',status:'pending',categoryId:activeAutoCat};modal(`<h2>${id?'Editar registro':'Nuevo registro del auto'}</h2><form class="planner-form" id="autoForm"><label>Concepto<input id="aTitle" required value="${esc(r.title)}" placeholder="Ej. Cambio de aceite"></label><div class="planner-form-grid"><label>Fecha<input id="aDate" type="date" value="${r.date||''}"></label><label>Kilometraje<input id="aKm" type="number" min="0" value="${r.mileage||''}"></label></div><div class="planner-form-grid"><label>Costo / presupuesto<input id="aCost" type="number" min="0" step="0.01" value="${r.cost||''}"></label><label>Estado<select id="aStatus"><option value="pending" ${r.status==='pending'?'selected':''}>Pendiente</option><option value="done" ${r.status==='done'?'selected':''}>Realizado</option></select></label></div><div class="planner-form-grid"><label>Próxima fecha<input id="aNextDate" type="date" value="${r.nextDate||''}"></label><label>Próximo kilometraje<input id="aNextKm" type="number" min="0" value="${r.nextKm||''}"></label></div><label>Notas<textarea id="aNotes">${esc(r.notes||'')}</textarea></label><div class="planner-form-actions">${id?`<button type="button" class="secondary" onclick="plannerDeleteAuto('${id}')">Eliminar</button>`:'<button type="button" class="secondary" onclick="closePlannerModal()">Cancelar</button>'}<button class="primary">Guardar</button></div></form>`);document.getElementById('autoForm').onsubmit=e=>{e.preventDefault();const data={title:document.getElementById('aTitle').value.trim(),date:document.getElementById('aDate').value,mileage:Number(document.getElementById('aKm').value||0),cost:Number(document.getElementById('aCost').value||0),nextDate:document.getElementById('aNextDate').value,nextKm:Number(document.getElementById('aNextKm').value||0),notes:document.getElementById('aNotes').value.trim(),status:document.getElementById('aStatus').value,categoryId:activeAutoCat};if(id)Object.assign(r,data);else db.autoRecords.unshift({id:uid('a'),...data,createdAt:new Date().toISOString()});save();closeModal();renderAuto()}};
window.plannerDeleteAuto=id=>{if(!confirm('¿Eliminar este registro?'))return;db.autoRecords=db.autoRecords.filter(r=>r.id!==id);save();closeModal();renderAuto()};

window.miAgendaPlanner={exportData:()=>db,reset:()=>{db=seed();localStorage.setItem(KEY,JSON.stringify(db));activeNote=null;activeGoalCat=db.goalCategories[0].id;activeAutoCat=db.autoCategories[0].id;renderAll()}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',renderAll,{once:true});else renderAll();
})();